spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lishanquan/spring-cloud-config
          search-paths: respo
          username:
          password:
      label: master
  application:
    name: config-server
server:
  port: 8769